Version ceiling on fastcore because FT bug
Bug otherwise results in:
    data_dir = os.path.join(config["out_dir"], "data")
  File "<frozen posixpath>", line 77, in join
TypeError: expected str, bytes or os.PathLike object, not FT

No time to figure out root cause, but somehow default string value of out_dir is getting turned into fastcore's FT class, which is for XML use cases.